

KEY_FUNC key_func = {
     "$  keys",             

     0,                     
     0,                     
     AbortCommand,          
     0,                     
                   
     ClearAllMacros,        
     0,                     
     Rturn,                 
     NextLine,              
     BegNextLine,           
     BackSpace,             
     BackSpace,             
     0,                     
     Tab,                   
     0,                    
                   
     0,                     
     BackTab,               
     Quit,                  
     BlockToFile,           
     BlockExpandTabs,       
     ToggleRuler,           
     BlockTrimTrailing,     
     UndoDelete,            
     UnMarkBlock,           
     ToggleIndent,          
                   
     OverlayBlock,          
     PrintBlock,            
     0,                     
     0,                     
     0,                     
     0,                     
     AddLine,               
     SortBoxBlock,          
     DeleteLine,            
     FillBlock,             
                   
     DeleteBlock,           
     Help,                  
     JoinLine,              
     KopyBlock,             
     MarkLine,              
     0,                     
     0,                     
     0,                     
     0,                     
     0,                     
                   
     ToggleZ,               
     MarkStream,            
     CopyBlock,             
     ToggleWordWrap,        
     MarkBox,               
     NumberBlock,           
     MoveBlock,             
     BlockUpperCase,        84 keyboards, fmd */
     BlockLowerCase,        84 keyboards, fmd */
     BlockStripHiBit,       84 keyboards, fmd */
                   
     0,                     
     0,                     
     0,                     
     0,                     
     0,                     
     Help,                  
     Save,                  
     Quit,                  
     File,                  
     RepeatFindForward1,    
                   
     RepeatFindBackward1,   
     RepeatFindRegX,        
     SplitVertical,         
     SplitHorizontal,       
     NextWindow,            
     0,                     
     0,                     
     BegOfLine,             
     LineUp,                
     ScreenUp,              
                   
     0,                     
     CharLeft,              
     CenterWindow,          
     CharRight,             
     0,                     
     EndOfLine,             
     LineDown,              
     ScreenDown,            
     ToggleOverWrite,       
     DeleteChar,            
                   
     SaveMacro,             
     SaveAs,                
     LoadMacro,             
     EditFile,              
     FindForward,           
     FindBackward,          
     FindRegX,              
     ReplaceString,         
     SizeWindow,            
     PreviousWindow,        
                   
     ToggleSync,            
     ToggleEol,             
     ToggleCRLF,            
     ToggleTrailing,        
     ToggleSearchCase,      
     SetLeftMargin,         
     SetRightMargin,        
     SetParagraphMargin,    
     ZoomWindow,            
     NextHiddenWindow,      
                   
     DirList,               
     SetFileAttributes,     
     RecordMacro,           
     EditNextFile,          
     NextDirtyLine,         
     PrevDirtyLine,         
    
     RepeatFindRegXBackward,
     LeftJustify,           
     RightJustify,          
     CenterJustify,         
                   
     0,                     
     WordLeft,              
     WordRight,             
     BotOfScreen,           
     EndOfFile,             
     TopOfScreen,           
     SetMark1,              
     SetMark2,              
     SetMark3,              
     0,                     
                   
     0,                     
     0,                     
     0,                     
     0,                     
     0,                     
     0,                     
     DelEndOfLine,          
     DuplicateLine,         
     TopOfFile,             
     RepeatDiff,            
                   
     RepeatGrep,            
     DefineDiff,            
     DefineGrep,            
     0,                     
     DefineRegXGrep,        
     0,                     
     RepeatFindRegX,        
     ScrollUpLine,          
     PanUp,                 
     CenterLine,            
                   
     PanDn,                 
     ScrollDnLine,          
     0,                     
     StreamDeleteChar,      
     SetTabs,               
     0,                       */
     0,                     
     0,                     
     PanUp,                 
     HorizontalScreenLeft,  
                   
     0,                     
     PanLeft,               
     0,                     
     PanRight,              
     0,                     
     0,                     
     PanDn,                 
     HorizontalScreenRight, 
     0,                     
     0,                     
                   
     0,                          
     ToggleSmartTabs,       
     0,                     
     ScrollUpLine,          
     ScrollDnLine,          
     Rturn,                
     PanLeft,               
     PanRight,              
     0,                     
     0,                     

 


     DateTimeStamp,         
     WordLeft,              
     FormatText,            
     ScreenDown,            
     CharRight,             
     LineUp,                
     WordRight,             
     DeleteChar,            
     BackSpace,             
     Tab,                   
     Help,                  
     TwoCharKey,            
     0,                     
     Rturn,                 
     AddLine,               
     0,                     
     Pause,                 
     0,                     
     ScreenUp,              
     CharLeft,              
     WordDelete,            
     UndoDelete,            
     ToggleOverWrite,       
     ScrollUpLine,          
     LineDown,              
     DeleteLine,            
     ScrollDnLine,          
     AbortCommand,          
     RedrawScreen,          
     ParenBalance,          

     0,                     
     SplitLine,             
     GotoMark1,             
     GotoMark2,             
     GotoMark3,             
     0,                     
     0,                     
     0,                     
     0,                     
     0,                     

     0,                     
     0,                     
     0,                     
     0,                     
     DefineGrep,            
     RepeatGrep,            
     0,                     
     0,                     
     ToggleTabInflate,      
     0,                     

     0,                     
     BlockIndentTabs,       
     0,                     
     0,                     
     0,                     
     0,                     
     0,                     
     0,                     
     0,                     
     SwapBlock,             

     RepeatDiff,            
     0,                     
     0,                     
     0,                     
     JumpToLine,            
     0,                     
     0,                     
     0,                     
     0,                     
     0,                     

     0,                     
     0,                     
     0,                     
     0,                     
     BlockCompressTabs,     
     0,                     
     0,                     
     0,                     
     0,                     
     BlockRot13,            84 keyboards, fmd */

     BlockFixUUE,           84 keyboards, fmd */
     BlockEmailReply        84 keyboards, fmd */
};



TWO_KEY two_key_list = {
   "$twokey",
   { { _CNTRL_K, 'q', Quit },       
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },  
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },  
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },  
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },  
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },  
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },
   { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 }, { 0, 0, 0 },  
   { 0, 0, 0 }, { 0, 0, 0 } }
};
